### ISSUE TITLE
Beneficiaries Not Deleting

### ISSUE THREAD

**Issue by Happs80** [humansis/front#132]
When clicking on delete beside a BNFs household, there is no confirmation and delete does not seem to work.

**Comment by blazekv** [comment]
@Happs80  I tried it on actual dev branch and it seems it is OK. Could you please confirm, that I tried correct scenario? 

![delete-beneficiar](https://user-images.githubusercontent.com/5405360/77224868-fa1a7f00-6b69-11ea-84ef-f8f1e626ccbc.gif)

**Comment by Happs80** [comment]
Tried on the demo server. The confirmation box appears. You can click confirm. But nothing happens.

![20200321_212300](https://user-images.githubusercontent.com/31128624/77229111-61621e80-6bbe-11ea-9b55-063d825b9d1a.gif)

**Comment by blazekv** [comment]
@Happs80 I tested on stage and it seems that it is working correctly. I tried multiple deletion and single deletion. We should wait until deploy production and then we could probably close this.

**Comment by Happs80** [comment]
Noted. Will do.

**Comment by Happs80** [comment]
Seems to be fixed in firefox. Caching issue on Chrome.
