### ISSUE TITLE
Change Display Text on Front, Project and Distribution Pages

### ISSUE THREAD

**Issue by Happs80** [humansis/front#157]
Front Page

![Front Page](https://user-images.githubusercontent.com/31128624/77635063-8d95ea80-6f84-11ea-9a13-9533e1d1119e.jpg)

**Comment by blazekv** [comment]
@Happs80 Could you please provide translations to another languages?
`add_distribution_beneficiaries_reached = 'المستفيدون الذين تم الوصول إليهم'`
`add_distribution_beneficiaries_reached = 'Bénéficaires atteints'`
`add_distribution_beneficiaries_reached = 'Полученные бенефициары'`

There is also somewhere text **Percentage of beneficiaries reached**. I dont know where it is, but maybe there should be also change to unique. Is it right?

**Comment by Happs80** [comment]
Project Page

![Project Page](https://user-images.githubusercontent.com/31128624/77635090-9b4b7000-6f84-11ea-96df-ec3f84acf336.jpg)

**Comment by Happs80** [comment]
Distribution Page

![Distribution Page](https://user-images.githubusercontent.com/31128624/77635129-aacab900-6f84-11ea-9893-a6d1a701cfbb.jpg)
