### ISSUE TITLE
Report Page Flicks Back and Forth When Opening

### ISSUE THREAD

**Issue by Happs80** [humansis/front#160]
When opening the report page, and clicking on either Project or Distribution Report, it immediately selects back to Country page.

**Comment by Happs80** [comment]
[20191216_103439.zip](https://github.com/humansis/front/files/3967367/20191216_103439.zip)

**Comment by blazekv** [comment]
It is connected to some strange code in HTTP requests. I will try to find out why there is such a strange code. I managed to fix it, but I was forced to change some core code in HTTP service. It could break so many things.

**Comment by blazekv** [comment]
![flicker](https://user-images.githubusercontent.com/5405360/77225893-e83dd980-6b73-11ea-8422-cf3dfa50851b.gif)

**Comment by blazekv** [comment]
![flicker](https://user-images.githubusercontent.com/5405360/77225951-613d3100-6b74-11ea-83ae-9b32964522d3.gif)
