### ISSUE TITLE
Add application version information

### ISSUE THREAD

**Issue by blazekv** [humansis/front#229]

**Comment by Happs80** [comment]
A little number in the bottom right?

**Comment by blazekv** [comment]
Right now it is under main title at login page. It should be somewhere on login page. I can move ti to left bottom corner if you want. Right corner is occupied by Google Captcha.

![2020-04-01 13_00_04-Humansis](https://user-images.githubusercontent.com/5405360/78130154-0b407700-7419-11ea-8972-e05d8d10dfbe.png)
