### ISSUE TITLE
Separate components into lazy loaded modules

### ISSUE THREAD

**Issue by blazekv** [humansis/front#253]
It should speed up load of application because modules which are not used are not loaded.

**Comment by blazekv** [comment]
I am adding screenshot of audit (before and after).

![2020-04-25 14_30_55-Window](https://user-images.githubusercontent.com/5405360/80280384-0911c580-8704-11ea-8f43-a9b0119c0623.png)

**Comment by blazekv** [comment]
@Happs80 I did first important part of this issue. Now project is separated into lazy loaded modules. To reduce size of loaded bundles it is necessary to rearrange imports, which will be much more time consuming (especially checking if everything works cause we dont have tests).

I will merge this and create new issue for rearrange imports.

**Comment by Happs80** [comment]
Nice.
